export default dummy = [
  {medName: 'Adderall XR',
   strength: '20 mg',
   img: 'https://www.additudemag.com/wp-content/uploads/2017/02/adderall_xr_25mg.jpg',
   direction: 'Take 1 Capsule By Mouth Once A Day in the Morning',
  },
  {medName: 'Simvastatin',
   strength: '10 mg',
   img: 'https://img.medscapestatic.com/pi/features/drugdirectory/octupdate/AUR00510.jpg',
   direction: 'Take 1 Tablet By Mouth Once A Day in the Evening',
  },
  {medName: 'Losartan',
   strength: '50 mg',
   img: 'https://img.medscapestatic.com/pi/features/drugdirectory/octupdate/CBR07010.jpg',
   direction: 'Take 1 Tablet By Mouth Once A Day',
  },
  {medName: 'Alendronate',
   strength: '70 mg',
   img: 'https://img.medscapestatic.com/pi/features/drugdirectory/octupdate/CIP02240.jpg',
   direction: 'Take 1 Tablet By Mouth Once A Week',
  },
  {medName: 'Amphetamine Salts',
   strength: '10 mg',
   img: 'https://www.cvs.com/webcontent/images/drug/DrugItem_31.JPG',
   direction: 'Take 1 Tablet By Mouth Once A Day at 2PM',
  }
]